spring:
  application:
    name: reservation-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking_db_reservations
    username: david
    password: passer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/booking-realm
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  auth:
    converter:
      resource-id: booking-client
      principle-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8083