spring:
  application:
    name: reservation-service
  #config:
  #  import: optional:configserver:http://localhost:8089
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking_db_reservations
    username: david
    password: passer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083